# docker-compose.yml
version: "3"

services:
  expo:
    image: node:14.5-buster
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=192.168.1.69
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.69
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    command: sh -c "npm uninstall -g expo-cli && npm install -g expo-cli && npm install && npm start"